/**
 * B16 - Access Logging System
 * 
 * Logs user access to different views and profile generation
 * Maintains both Access Log and Profile Log in the same spreadsheet
 */

/**
 * Access Log spreadsheet configuration
 */
const ACCESS_LOG_CONFIG = {
  spreadsheetId: '1sE1N0nnqFh_EWN4konURXLP2bEj0rqF3JIyOnpPmWJU',
  accessSheetName: 'Access Log',
  profileSheetName: 'Profile Log',
  columns: {
    access: {
      KEY: 'A',           // view_MM/DD/YY from timestamp
      VIEW: 'B',          // OEM, Agency, Vendor, Report Generator, or Reports
      EMAIL: 'C',         // User email
      TIMESTAMP: 'D'      // Full timestamp
    },
    profile: {
      KEY: 'A',           // Profile Type + Letterhead + timestamp
      VIEW: 'B',          // OEM, Vendor, or Agency
      PROFILE_TYPE: 'C',  // Profile Type
      LETTERHEAD: 'D',    // Letterhead (GSA or ITVMO)
      PROFILE_LINK: 'E',  // Profile Link
      GENERATED_BY: 'F',  // Generated By
      TIMESTAMP: 'G'      // Generation Timestamp
    }
  }
};

/**
 * Log user access to different views
 * 
 * @param {string} view - View accessed: 'OEM', 'Agency', 'Vendor', 'Report Generator', or 'Reports'
 */
function logUserAccess(view) {
  try {
    console.log(`📊 Logging user access to ${view} view`);
    
    // Open the Access Log spreadsheet
    const ss = SpreadsheetApp.openById(ACCESS_LOG_CONFIG.spreadsheetId);
    console.log(`📊 Opened spreadsheet with ID: ${ACCESS_LOG_CONFIG.spreadsheetId}`);
    
    const sheet = ss.getSheetByName(ACCESS_LOG_CONFIG.accessSheetName);
    
    if (!sheet) {
      console.error(`❌ Sheet '${ACCESS_LOG_CONFIG.accessSheetName}' not found`);
      const availableSheets = ss.getSheets().map(s => s.getName());
      console.log('Available sheets:', availableSheets);
      throw new Error(`Sheet '${ACCESS_LOG_CONFIG.accessSheetName}' not found in spreadsheet`);
    }
    console.log(`✅ Found sheet: ${ACCESS_LOG_CONFIG.accessSheetName}`);
    
    // Generate timestamp and formatted date
    const timestamp = new Date();
    const month = (timestamp.getMonth() + 1).toString().padStart(2, '0');
    const day = timestamp.getDate().toString().padStart(2, '0');
    const year = timestamp.getFullYear().toString().slice(-2);
    const dateString = `${month}/${day}/${year}`;
    
    // Generate key: view_MM/DD/YY
    const key = `${view}_${dateString}`;
    
    // Get current user email
    const userEmail = Session.getActiveUser().getEmail();
    
    // Prepare row data according to column structure
    const rowData = [
      key,              // A: Key (view_MM/DD/YY)
      view,             // B: View
      userEmail,        // C: Email
      timestamp         // D: Timestamp
    ];
    
    console.log(`📊 Attempting to append row:`, rowData);
    
    // Append the new row
    sheet.appendRow(rowData);
    
    console.log(`✅ User access logged: ${key} by ${userEmail}`);
    
  } catch (error) {
    console.error('❌ Error logging user access:', error);
    console.error('Error details:', error.toString());
    console.error('Stack trace:', error.stack);
    // Don't fail the main functionality if logging fails
  }
}

/**
 * Log profile generation (moved from B14_ProfileGenerator.js)
 * 
 * @param {string} profileType - Type of profile
 * @param {string} view - Entity view: 'OEM', 'Vendor', or 'Agency'  
 * @param {string} profileLink - Google Doc URL
 * @param {string} entityName - Name of entity for key generation
 * @param {string} letterhead - Letterhead type (GSA or ITVMO)
 */
function logProfileGeneration(profileType, view, profileLink, entityName, letterhead) {
  try {
    console.log(`📊 Logging profile generation to spreadsheet`);
    
    // Open the Profile Log spreadsheet
    const ss = SpreadsheetApp.openById(ACCESS_LOG_CONFIG.spreadsheetId);
    const sheet = ss.getSheetByName(ACCESS_LOG_CONFIG.profileSheetName);
    
    if (!sheet) {
      throw new Error(`Sheet '${ACCESS_LOG_CONFIG.profileSheetName}' not found in spreadsheet`);
    }
    
    // Generate timestamp and key
    const timestamp = new Date();
    const timestampString = timestamp.toISOString();
    const key = `${profileType}_${letterhead}_${timestampString}`;
    
    // Get current user email
    const userEmail = Session.getActiveUser().getEmail();
    
    // Prepare row data according to column structure
    const rowData = [
      key,              // A: Key (Profile Type + Letterhead + timestamp)
      view,             // B: View (OEM, Vendor, Agency)
      profileType,      // C: Profile Type
      letterhead,       // D: Letterhead (GSA or ITVMO)
      profileLink,      // E: Profile Link
      userEmail,        // F: Generated By
      timestamp         // G: Generation Timestamp
    ];
    
    // Append the new row
    sheet.appendRow(rowData);
    
    console.log(`✅ Profile generation logged: ${key} for ${entityName} by ${userEmail}`);
    
  } catch (error) {
    console.error('Error logging profile generation:', error);
    // Don't fail the profile generation if logging fails
  }
}

/**
 * Helper function to log access when OEM view is accessed
 */
function logOEMAccess() {
  try {
    logUserAccess('OEM');
    return { success: true, message: 'OEM access logged' };
  } catch (error) {
    console.error('❌ logOEMAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Helper function to log access when Agency view is accessed
 */
function logAgencyAccess() {
  try {
    logUserAccess('Agency');
    return { success: true, message: 'Agency access logged' };
  } catch (error) {
    console.error('❌ logAgencyAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Helper function to log access when Vendor view is accessed
 */
function logVendorAccess() {
  try {
    logUserAccess('Vendor');
    return { success: true, message: 'Vendor access logged' };
  } catch (error) {
    console.error('❌ logVendorAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Helper function to log access when Report Generator is accessed
 */
function logReportGeneratorAccess() {
  try {
    logUserAccess('Report Generator');
    return { success: true, message: 'Report Generator access logged' };
  } catch (error) {
    console.error('❌ logReportGeneratorAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Helper function to log access when Reports view is accessed
 */
function logReportsAccess() {
  try {
    logUserAccess('Reports');
    return { success: true, message: 'Reports access logged' };
  } catch (error) {
    console.error('❌ logReportsAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Helper function to log general app access
 * Can be called when the main dashboard is loaded
 */
function logAppAccess() {
  try {
    logUserAccess('Dashboard');
    return { success: true, message: 'Dashboard access logged' };
  } catch (error) {
    console.error('❌ logAppAccess failed:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Simple test function that can be called from client
 * Returns success status
 */
function testLogFromClient() {
  try {
    console.log('🧪 testLogFromClient called');
    
    // Test step by step
    const ss = SpreadsheetApp.openById(ACCESS_LOG_CONFIG.spreadsheetId);
    console.log('✅ Spreadsheet opened');
    
    const sheet = ss.getSheetByName(ACCESS_LOG_CONFIG.accessSheetName);
    console.log('✅ Sheet found:', sheet ? 'YES' : 'NO');
    
    if (!sheet) {
      const allSheets = ss.getSheets().map(s => s.getName());
      return { success: false, message: `Sheet not found. Available: ${allSheets.join(', ')}` };
    }
    
    const userEmail = Session.getActiveUser().getEmail();
    console.log('📧 User email:', userEmail);
    
    if (!userEmail) {
      return { success: false, message: 'User email is empty - permission issue' };
    }
    
    const timestamp = new Date();
    const month = (timestamp.getMonth() + 1).toString().padStart(2, '0');
    const day = timestamp.getDate().toString().padStart(2, '0');
    const year = timestamp.getFullYear().toString().slice(-2);
    const dateString = `${month}/${day}/${year}`;
    const key = `WebTest_${dateString}`;
    
    const rowData = [key, 'WebTest', userEmail, timestamp];
    console.log('📊 About to append:', rowData);
    
    sheet.appendRow(rowData);
    console.log('✅ Row appended successfully');
    
    return { success: true, message: `Successfully logged: ${key} by ${userEmail}` };
  } catch (error) {
    console.error('❌ testLogFromClient error:', error);
    return { success: false, message: error.toString() };
  }
}

/**
 * Test function to verify access logging is working
 * Can be run directly from the Apps Script editor
 */
function testAccessLogging() {
  try {
    console.log('🧪 Testing access logging...');
    
    // Test if we can open the spreadsheet
    const ss = SpreadsheetApp.openById(ACCESS_LOG_CONFIG.spreadsheetId);
    console.log('✅ Spreadsheet opened successfully');
    
    // List all available sheet names
    const allSheets = ss.getSheets().map(s => s.getName());
    console.log('📋 Available sheets:', allSheets);
    
    // Test if we can find the sheet
    const sheet = ss.getSheetByName(ACCESS_LOG_CONFIG.accessSheetName);
    if (!sheet) {
      console.error('❌ Sheet not found: ' + ACCESS_LOG_CONFIG.accessSheetName);
      console.log('Available sheets:', allSheets);
      return false;
    }
    console.log('✅ Sheet found: ' + ACCESS_LOG_CONFIG.accessSheetName);
    
    // Test writing a row directly
    const timestamp = new Date();
    const month = (timestamp.getMonth() + 1).toString().padStart(2, '0');
    const day = timestamp.getDate().toString().padStart(2, '0');
    const year = timestamp.getFullYear().toString().slice(-2);
    const dateString = `${month}/${day}/${year}`;
    const key = `DirectTest_${dateString}`;
    const userEmail = Session.getActiveUser().getEmail();
    
    console.log('📧 User email:', userEmail);
    console.log('🔑 Generated key:', key);
    
    const rowData = [key, 'DirectTest', userEmail, timestamp];
    console.log('📊 Row data to append:', rowData);
    
    sheet.appendRow(rowData);
    console.log('✅ Test row written successfully');
    
    return true;
  } catch (error) {
    console.error('❌ Test failed:', error);
    console.error('Error details:', error.toString());
    console.error('Stack trace:', error.stack);
    return false;
  }
}

/**
 * Simple direct test - just append a row with current time
 */
function simpleDirectTest() {
  const ss = SpreadsheetApp.openById('1sE1N0nnqFh_EWN4konURXLP2bEj0rqF3JIyOnpPmWJU');
  const sheet = ss.getSheetByName('Access Log');
  const now = new Date();
  sheet.appendRow(['SimpleTest', 'Test', Session.getActiveUser().getEmail(), now]);
  console.log('Simple test completed at', now);
}

/**
 * Debug function to list all available sheet names
 */
function listAllSheets() {
  try {
    const ss = SpreadsheetApp.openById('1sE1N0nnqFh_EWN4konURXLP2bEj0rqF3JIyOnpPmWJU');
    const sheets = ss.getSheets();
    console.log('📋 Total sheets found:', sheets.length);
    sheets.forEach((sheet, index) => {
      console.log(`${index + 1}. "${sheet.getName()}" (ID: ${sheet.getSheetId()})`);
    });
    return sheets.map(s => ({name: s.getName(), id: s.getSheetId()}));
  } catch (error) {
    console.error('❌ Error listing sheets:', error);
    return [];
  }
}

/**
 * Test with explicit sheet name check
 */
function testWithSheetCheck() {
  const ss = SpreadsheetApp.openById('1sE1N0nnqFh_EWN4konURXLP2bEj0rqF3JIyOnpPmWJU');
  
  // List all sheets
  const allSheets = ss.getSheets().map(s => s.getName());
  console.log('Available sheets:', allSheets);
  
  // Try different possible names
  const possibleNames = ['Access Log', 'AccessLog', 'Access_Log', 'access log', 'access_log'];
  
  for (const name of possibleNames) {
    try {
      const sheet = ss.getSheetByName(name);
      if (sheet) {
        console.log(`✅ Found sheet with name: "${name}"`);
        const now = new Date();
        sheet.appendRow(['TestWithCheck', 'Test', Session.getActiveUser().getEmail(), now]);
        console.log('✅ Successfully wrote to sheet');
        return true;
      }
    } catch (error) {
      console.log(`❌ Failed with sheet name: "${name}" - ${error.message}`);
    }
  }
  
  console.log('❌ Could not find any matching sheet');
  return false;
}

/**
 * SIMPLE TEST - Call this from web to see if basic web->script communication works
 */
function alertTest() {
  const now = new Date().toLocaleString();
  return `ALERT TEST SUCCESS at ${now}`;
}

/**
 * SIMPLE LOG TEST - Just writes one row with "WebCall" prefix
 */
function simpleWebLogTest() {
  try {
    const ss = SpreadsheetApp.openById('1sE1N0nnqFh_EWN4konURXLP2bEj0rqF3JIyOnpPmWJU');
    const sheet = ss.getSheetByName('Access Log');
    const now = new Date();
    const userEmail = Session.getActiveUser().getEmail();
    sheet.appendRow([`WebCall_${now.getTime()}`, 'WebTest', userEmail, now]);
    return `SUCCESS: Logged at ${now.toLocaleString()}`;
  } catch (error) {
    return `ERROR: ${error.toString()}`;
  }
}

/**
 * SIMPLE ACCESS LOG TEST - Test the actual access logging functions
 */
function simpleAccessLogTest() {
  try {
    // Test the main logUserAccess function directly
    logUserAccess('TestAccess');
    return `SUCCESS: Access logged via logUserAccess at ${new Date().toLocaleString()}`;
  } catch (error) {
    return `ERROR: ${error.toString()}`;
  }
}

/**
 * SIMPLE OEM ACCESS TEST - Test OEM access logging specifically
 */
function simpleOEMAccessTest() {
  try {
    const result = logOEMAccess();
    return `SUCCESS: OEM access logged - ${result.message} at ${new Date().toLocaleString()}`;
  } catch (error) {
    return `ERROR: ${error.toString()}`;
  }
}